/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.EduSys.ui;

import com.EduSys.uitils.*;
import com.EduSys.uitils.XImage;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Lê Minh Khôi
 */
public class EduSys_JFrame extends javax.swing.JFrame {

    void init() {
        setSize(1000, 600);
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        setTitle("EduSys - Hệ Quản Lý Đào Tạo");
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongho.setText(format.format(new Date()));
            }
        }).start();
        this.openChao();
        this.openDangNhap();

    }

    /**
     * Creates new form EduSys_JFrame
     */
    public EduSys_JFrame() {
        initComponents();
        init();
    }

    void openChao() {
        new Chao_JDialog(this, true).setVisible(true);
    }

    void openDangNhap() {
        new DangNhap_JDialog(this, true).setVisible(true);
    }

    void doiMatKhau() {
        if (Auth.isLogin()) {
            new DoiMatKhau_JDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }
    void openDangXuat(){
        Auth.clear();
        new DangNhap_JDialog(this, true).setVisible(true);
    }

    void openKetThuc(){
        if (MsgBox.confirm(this, "Bạn có muốn kết thúc không?")) {
            System.exit(0);
        }
    }
    void openNhanVien() {
        if (Auth.isLogin()) {
            new NhanVien_JDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openHuongDan() {
         try {
            Desktop.getDesktop().browse(new File("help\\help.html").toURI());
        } catch (Exception e) {
            MsgBox.alert(this, "không tìm thấy file hướng dẫn!");
        }
    }

    void openGioiThieu() {
         try {
            Desktop.getDesktop().browse(new File("help\\GioiThieu.html").toURI());
        } catch (Exception e) {
            MsgBox.alert(this, "không tìm thấy file hướng dẫn!");
        }
    }
    void openChuyenDe() {
        if (Auth.isLogin()) {
            new ChuyenDe_JDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openNguoiHoc() {
        if (Auth.isLogin()) {
            new NguoiHoc_JDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openKhoaHoc() {
        if (Auth.isLogin()) {
            new KhoaHoc_JDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openThongKe(int index) {
        if (Auth.isLogin()) {
            if (index == 3 && !Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền xem doanh thu");
                return; 
            }
            ThongKe_JDialog tk = new ThongKe_JDialog(this, true);
            tk.selectTab(index);
            tk.setVisible(true);
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }

    }
    void openHocVien(){
        if (Auth.isLogin()) {
            new HocVien_JDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDX = new javax.swing.JButton();
        btnKetthuc = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnChuyende = new javax.swing.JButton();
        btnNguoihoc = new javax.swing.JButton();
        btnKhoahoc = new javax.swing.JButton();
        btnHocvien = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnHuongdan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDongho = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        mniDangnhap = new javax.swing.JMenuItem();
        mniDangxuat = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniDoiMK = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniKetthuc = new javax.swing.JMenuItem();
        mniChuyende = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mniKhoahoc = new javax.swing.JMenuItem();
        mniNguoihoc = new javax.swing.JMenuItem();
        mniHocvien = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniNhanvien = new javax.swing.JMenuItem();
        mnuThongke = new javax.swing.JMenu();
        mniBangdiem = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniLuongnguoihoc = new javax.swing.JMenuItem();
        mniDiemchuyende = new javax.swing.JMenuItem();
        mniDoanhthu = new javax.swing.JMenuItem();
        mnuTrogiup = new javax.swing.JMenu();
        mniHuongdan = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mniGioithieusanpham = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        btnDX.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Exit.png")); // NOI18N
        btnDX.setText("Đăng xuất");
        btnDX.setFocusable(false);
        btnDX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDX.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDXActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDX);

        btnKetthuc.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Stop.png")); // NOI18N
        btnKetthuc.setText("Kết thúc");
        btnKetthuc.setFocusable(false);
        btnKetthuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetthuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetthucActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKetthuc);
        jToolBar1.add(jSeparator1);

        btnChuyende.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\List.png")); // NOI18N
        btnChuyende.setText("Chuyên đề");
        btnChuyende.setFocusable(false);
        btnChuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyendeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChuyende);

        btnNguoihoc.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Users.png")); // NOI18N
        btnNguoihoc.setText("Người học");
        btnNguoihoc.setFocusable(false);
        btnNguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoihocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNguoihoc);

        btnKhoahoc.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Address book.png")); // NOI18N
        btnKhoahoc.setText("Khóa học");
        btnKhoahoc.setFocusable(false);
        btnKhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoahocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhoahoc);

        btnHocvien.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\User.png")); // NOI18N
        btnHocvien.setText("Học viên");
        btnHocvien.setFocusable(false);
        btnHocvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHocvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocvienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHocvien);
        jToolBar1.add(jSeparator2);

        btnHuongdan.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Help.png")); // NOI18N
        btnHuongdan.setText("Hướng dẫn");
        btnHuongdan.setFocusable(false);
        btnHuongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongdanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHuongdan);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Hệ Quản Lý Đào Tạo");

        lblDongho.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Bo_Icon\\Alarm.png")); // NOI18N
        lblDongho.setText("9:07:47 AM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongho, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lblDongho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Bo_Icon\\conong.png")); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenu5.setText("Hệ thống");

        mniDangnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangnhap.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Open door.png")); // NOI18N
        mniDangnhap.setText("Đăng nhập");
        jMenu5.add(mniDangnhap);

        mniDangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangxuat.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Exit.png")); // NOI18N
        mniDangxuat.setText("Đăng xuất");
        mniDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangxuatActionPerformed(evt);
            }
        });
        jMenu5.add(mniDangxuat);
        jMenu5.add(jSeparator3);

        mniDoiMK.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Refresh.png")); // NOI18N
        mniDoiMK.setText("Đổi mật khẩu");
        mniDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMKActionPerformed(evt);
            }
        });
        jMenu5.add(mniDoiMK);
        jMenu5.add(jSeparator4);

        mniKetthuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniKetthuc.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Stop.png")); // NOI18N
        mniKetthuc.setText("Kết thúc");
        jMenu5.add(mniKetthuc);

        jMenuBar1.add(jMenu5);

        mniChuyende.setText("Quản lý");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\List.png")); // NOI18N
        jMenuItem1.setText("Chuyên đề");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mniChuyende.add(jMenuItem1);

        mniKhoahoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniKhoahoc.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Address book.png")); // NOI18N
        mniKhoahoc.setText("Khóa học");
        mniKhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhoahocActionPerformed(evt);
            }
        });
        mniChuyende.add(mniKhoahoc);

        mniNguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNguoihoc.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Users.png")); // NOI18N
        mniNguoihoc.setText("Người học");
        mniNguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNguoihocActionPerformed(evt);
            }
        });
        mniChuyende.add(mniNguoihoc);

        mniHocvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniHocvien.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\User.png")); // NOI18N
        mniHocvien.setText("Học viên");
        mniHocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHocvienActionPerformed(evt);
            }
        });
        mniChuyende.add(mniHocvien);
        mniChuyende.add(jSeparator5);

        mniNhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNhanvien.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Unknown person.png")); // NOI18N
        mniNhanvien.setText("Nhân viên");
        mniNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanvienActionPerformed(evt);
            }
        });
        mniChuyende.add(mniNhanvien);

        jMenuBar1.add(mniChuyende);

        mnuThongke.setText("Thống kê");
        mnuThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThongkeActionPerformed(evt);
            }
        });

        mniBangdiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniBangdiem.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Bo_Icon\\Notes.png")); // NOI18N
        mniBangdiem.setText("Bảng điểm");
        mniBangdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBangdiemActionPerformed(evt);
            }
        });
        mnuThongke.add(mniBangdiem);
        mnuThongke.add(jSeparator6);

        mniLuongnguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniLuongnguoihoc.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Bo_Icon\\paste.png")); // NOI18N
        mniLuongnguoihoc.setText("Lượng người học");
        mniLuongnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLuongnguoihocActionPerformed(evt);
            }
        });
        mnuThongke.add(mniLuongnguoihoc);

        mniDiemchuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniDiemchuyende.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Bo_Icon\\Bar chart.png")); // NOI18N
        mniDiemchuyende.setText("Điểm chuyên đề");
        mniDiemchuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiemchuyendeActionPerformed(evt);
            }
        });
        mnuThongke.add(mniDiemchuyende);

        mniDoanhthu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniDoanhthu.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Bo_Icon\\Price list.png")); // NOI18N
        mniDoanhthu.setText("Doanh thu");
        mniDoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhthuActionPerformed(evt);
            }
        });
        mnuThongke.add(mniDoanhthu);

        jMenuBar1.add(mnuThongke);

        mnuTrogiup.setText("Trợ giúp");

        mniHuongdan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniHuongdan.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Help.png")); // NOI18N
        mniHuongdan.setText("Hướng dẫn");
        mnuTrogiup.add(mniHuongdan);
        mnuTrogiup.add(jSeparator7);

        mniGioithieusanpham.setIcon(new javax.swing.ImageIcon("D:\\FPT Polytechnic\\Ky_4\\BLOCK_1\\Du_an_mau\\EduSys\\logos\\Home.png")); // NOI18N
        mniGioithieusanpham.setText("Giới thiệu sản phẩm");
        mniGioithieusanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioithieusanphamActionPerformed(evt);
            }
        });
        mnuTrogiup.add(mniGioithieusanpham);

        jMenuBar1.add(mnuTrogiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyendeActionPerformed
        openChuyenDe();
    }//GEN-LAST:event_btnChuyendeActionPerformed

    private void btnKhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoahocActionPerformed
        openKhoaHoc();
    }//GEN-LAST:event_btnKhoahocActionPerformed

    private void mniDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangxuatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniDangxuatActionPerformed

    private void mniBangdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBangdiemActionPerformed
        openThongKe(0);
    }//GEN-LAST:event_mniBangdiemActionPerformed

    private void mniDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMKActionPerformed
        this.doiMatKhau();
    }//GEN-LAST:event_mniDoiMKActionPerformed

    private void mniNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanvienActionPerformed
        this.openNhanVien();
    }//GEN-LAST:event_mniNhanvienActionPerformed

    private void btnHuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongdanActionPerformed
        this.openHuongDan();
    }//GEN-LAST:event_btnHuongdanActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        openChuyenDe();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnNguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoihocActionPerformed
        openNguoiHoc();
    }//GEN-LAST:event_btnNguoihocActionPerformed

    private void mniNguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNguoihocActionPerformed
        openNguoiHoc();
    }//GEN-LAST:event_mniNguoihocActionPerformed

    private void mniKhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhoahocActionPerformed
        openKhoaHoc();
    }//GEN-LAST:event_mniKhoahocActionPerformed

    private void mnuThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThongkeActionPerformed
       
    }//GEN-LAST:event_mnuThongkeActionPerformed

    private void mniDiemchuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiemchuyendeActionPerformed
        openThongKe(2);
    }//GEN-LAST:event_mniDiemchuyendeActionPerformed

    private void mniLuongnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLuongnguoihocActionPerformed
        openThongKe(1);
    }//GEN-LAST:event_mniLuongnguoihocActionPerformed

    private void mniDoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhthuActionPerformed
        openThongKe(3);
    }//GEN-LAST:event_mniDoanhthuActionPerformed

    private void btnDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDXActionPerformed
        openDangXuat();
    }//GEN-LAST:event_btnDXActionPerformed

    private void btnKetthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetthucActionPerformed
        openKetThuc();
    }//GEN-LAST:event_btnKetthucActionPerformed

    private void btnHocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocvienActionPerformed
        openHocVien();
    }//GEN-LAST:event_btnHocvienActionPerformed

    private void mniHocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHocvienActionPerformed
       openHocVien();
    }//GEN-LAST:event_mniHocvienActionPerformed

    private void mniGioithieusanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioithieusanphamActionPerformed
        openGioiThieu();
    }//GEN-LAST:event_mniGioithieusanphamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EduSys_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyende;
    private javax.swing.JButton btnDX;
    private javax.swing.JButton btnHocvien;
    private javax.swing.JButton btnHuongdan;
    private javax.swing.JButton btnKetthuc;
    private javax.swing.JButton btnKhoahoc;
    private javax.swing.JButton btnNguoihoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDongho;
    private javax.swing.JMenuItem mniBangdiem;
    private javax.swing.JMenu mniChuyende;
    private javax.swing.JMenuItem mniDangnhap;
    private javax.swing.JMenuItem mniDangxuat;
    private javax.swing.JMenuItem mniDiemchuyende;
    private javax.swing.JMenuItem mniDoanhthu;
    private javax.swing.JMenuItem mniDoiMK;
    private javax.swing.JMenuItem mniGioithieusanpham;
    private javax.swing.JMenuItem mniHocvien;
    private javax.swing.JMenuItem mniHuongdan;
    private javax.swing.JMenuItem mniKetthuc;
    private javax.swing.JMenuItem mniKhoahoc;
    private javax.swing.JMenuItem mniLuongnguoihoc;
    private javax.swing.JMenuItem mniNguoihoc;
    private javax.swing.JMenuItem mniNhanvien;
    private javax.swing.JMenu mnuThongke;
    private javax.swing.JMenu mnuTrogiup;
    // End of variables declaration//GEN-END:variables
}
